package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ComputeInterconnect is the Schema for the ComputeInterconnect API
type ComputeInterconnect struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ComputeInterconnectSpec   `json:"spec,omitempty"`
	Status ComputeInterconnectStatus `json:"status,omitempty"`
}

// ComputeInterconnectSpec defines the desired state of ComputeInterconnect.
type ComputeInterconnectSpec struct {
	// Administrative status of the interconnect. When this is set to true, the Interconnect is functional and can carry traffic. When set to false, no packets can be carried over the interconnect and no BGP routes are exchanged over it. By default, the status is set to true.
	AdminEnabled bool `json:"adminEnabled,omitempty" yaml:"adminEnabled,omitempty"`
	// Customer name, to put in the Letter of Authorization as the party authorized to request a crossconnect.
	CustomerName string `json:"customerName,omitempty" yaml:"customerName,omitempty"`
	// An optional description of this resource. Provide this property when you create the resource.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Type of interconnect, which can take one of the following values: - PARTNER: A partner-managed interconnection shared between customers though a partner. - DEDICATED: A dedicated physical interconnection with the customer. Note that a value IT_PRIVATE has been deprecated in favor of DEDICATED. Check the InterconnectType enum for the list of possible values.
	InterconnectType string `json:"interconnectType,omitempty" yaml:"interconnectType,omitempty"`
	// A fingerprint for the labels being applied to this Interconnect, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error 412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve an Interconnect.
	LabelFingerprint string `json:"labelFingerprint,omitempty" yaml:"labelFingerprint,omitempty"`
	// Labels for this resource. These can only be added or modified by the setLabels method. Each label key/value pair must comply with RFC1035. Label values may be empty.
	Labels map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	// Type of link requested, which can take one of the following values: - LINK_TYPE_ETHERNET_10G_LR: A 10G Ethernet with LR optics - LINK_TYPE_ETHERNET_100G_LR: A 100G Ethernet with LR optics. Note that this field indicates the speed of each of the links in the bundle, not the speed of the entire bundle. Check the LinkType enum for the list of possible values.
	LinkType string `json:"linkType,omitempty" yaml:"linkType,omitempty"`
	// URL of the InterconnectLocation object that represents where this connection is to be provisioned.
	Location string `json:"location,omitempty" yaml:"location,omitempty"`
	// Configuration that enables Media Access Control security (MACsec) on the Cloud Interconnect connection between Google and your on-premises router.
	Macsec map[string]interface{} `json:"macsec,omitempty" yaml:"macsec,omitempty"`
	// Enable or disable MACsec on this Interconnect connection. MACsec enablement fails if the MACsec object is not specified.
	MacsecEnabled bool `json:"macsecEnabled,omitempty" yaml:"macsecEnabled,omitempty"`
	// Email address to contact the customer NOC for operations and maintenance notifications regarding this Interconnect. If specified, this will be used for notifications in addition to all other forms described, such as Cloud Monitoring logs alerting and Cloud Notifications. This field is required for users who sign up for Cloud Interconnect using workforce identity federation.
	NocContactEmail string `json:"nocContactEmail,omitempty" yaml:"nocContactEmail,omitempty"`
	// The Project that this resource belongs to.
	ProjectRef map[string]interface{} `json:"projectRef,omitempty" yaml:"projectRef,omitempty"`
	// Indicates that this is a Cross-Cloud Interconnect. This field specifies the location outside of Google's network that the interconnect is connected to.
	RemoteLocation string `json:"remoteLocation,omitempty" yaml:"remoteLocation,omitempty"`
	// Optional. List of features requested for this Interconnect connection, which can take one of the following values: - IF_MACSEC If specified then the connection is created on MACsec capable hardware ports. If not specified, the default value is false, which allocates non-MACsec capable ports first if available. This parameter can be provided only with Interconnect INSERT. It isn't valid for Interconnect PATCH. Check the RequestedFeatures enum for the list of possible values.
	RequestedFeatures []string `json:"requestedFeatures,omitempty" yaml:"requestedFeatures,omitempty"`
	// Target number of physical links in the link bundle, as requested by the customer.
	RequestedLinkCount int32 `json:"requestedLinkCount,omitempty" yaml:"requestedLinkCount,omitempty"`
	// The ComputeInterconnect name. If not given, the metadata.name will be used.
	ResourceID string `json:"resourceID,omitempty" yaml:"resourceID,omitempty"`
}

// ComputeInterconnectStatus defines the observed state of ComputeInterconnect.
type ComputeInterconnectStatus struct {
	// Conditions represent the latest available observations of the resource's state.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
