package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MonitoringAlertPolicy represents a monitoring.cnrm.cloud.google.com MonitoringAlertPolicy resource.
type MonitoringAlertPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MonitoringAlertPolicySpec   `json:"spec,omitempty"`
	Status MonitoringAlertPolicyStatus `json:"status,omitempty"`
}

// MonitoringAlertPolicySpec defines the desired state of MonitoringAlertPolicy.
type MonitoringAlertPolicySpec struct {
	// Control over how this alert policy's notification channels are notified.
	AlertStrategy map[string]interface{} `json:"alertStrategy,omitempty" yaml:"alertStrategy,omitempty"`
	// How to combine the results of multiple conditions to
	// determine if an incident should be opened. Possible values: ["AND", "OR", "AND_WITH_MATCHING_RESOURCE"].
	Combiner string `json:"combiner,omitempty" yaml:"combiner,omitempty"`
	// A list of conditions for the policy. The conditions are combined by
	// AND or OR according to the combiner field. If the combined conditions
	// evaluate to true, then an incident is created. A policy can have from
	// one to six conditions.
	Conditions []map[string]interface{} `json:"conditions,omitempty" yaml:"conditions,omitempty"`
	// A short name or phrase used to identify the policy in
	// dashboards, notifications, and incidents. To avoid confusion, don't use
	// the same display name for multiple policies in the same project. The
	// name is limited to 512 Unicode characters.
	DisplayName string `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	// Documentation that is included with notifications and incidents related
	// to this policy. Best practice is for the documentation to include information
	// to help responders understand, mitigate, escalate, and correct the underlying
	// problems detected by the alerting policy. Notification channels that have
	// limited capacity might not show this documentation.
	Documentation map[string]interface{} `json:"documentation,omitempty" yaml:"documentation,omitempty"`
	// Whether or not the policy is enabled. The default is true.
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`
	NotificationChannels []map[string]interface{} `json:"notificationChannels,omitempty" yaml:"notificationChannels,omitempty"`
	// Immutable. Optional. The service-generated name of the resource. Used for acquisition only. Leave unset to create a new resource.
	ResourceID string `json:"resourceID,omitempty" yaml:"resourceID,omitempty"`
	// The severity of an alert policy indicates how important
	// incidents generated by that policy are. The severity level will be displayed on
	// the Incident detail page and in notifications. Possible values: ["CRITICAL", "ERROR", "WARNING"].
	Severity string `json:"severity,omitempty" yaml:"severity,omitempty"`
}

// MonitoringAlertPolicyStatus defines the observed state of MonitoringAlertPolicy.
type MonitoringAlertPolicyStatus struct {
	// Conditions represent the latest available observations of the resource's state.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
