package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AnalyticsAccount is the Schema for the AnalyticsAccount API
type AnalyticsAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AnalyticsAccountSpec   `json:"spec,omitempty"`
	Status AnalyticsAccountStatus `json:"status,omitempty"`
}

// AnalyticsAccountSpec defines the desired state of AnalyticsAccount.
type AnalyticsAccountSpec struct {
	// Required. Human-readable display name for this account.
	DisplayName string `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	// Redirect URI where the user will be sent after accepting Terms of Service.
	RedirectURI string `json:"redirectURI,omitempty" yaml:"redirectURI,omitempty"`
	// Country of business. Must be a Unicode CLDR region code.
	RegionCode string `json:"regionCode,omitempty" yaml:"regionCode,omitempty"`
	// The AnalyticsAccount name. It's generated by the service. Providing resource ID via this field indicates resource acquisition instead of creation.
	ResourceID string `json:"resourceID,omitempty" yaml:"resourceID,omitempty"`
}

// AnalyticsAccountStatus defines the observed state of AnalyticsAccount.
type AnalyticsAccountStatus struct {
	// Conditions represent the latest available observations of the resource's state.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
